Ticketinsystems/Controllers/DepartmentController.cs
using businesslogic.Dto;
using businesslogic.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Ticketinsystems.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService DepartmentService;
        private readonly IEmpolyeeServices empolyeeServices;
        public DepartmentController(IDepartmentService _departmentService, IEmpolyeeServices _empolyeeServices)
        {
            DepartmentService = _departmentService;
            empolyeeServices = _empolyeeServices;
        }
        [Authorize(Roles = "LoadDepartment")]
        public ActionResult Index1()
        {
         
            return View();
        }
        [Authorize(Roles = "LoadDepartment")]
        //public ActionResult List()
        //{
        //    return Json(DepartmentService.Load(), JsonRequestBehavior.AllowGet);
        //    //return View("List", DepartmentService.Load());
        //}
        //[Authorize(Roles = "LoadDepartment")]
        //public ActionResult List()
        //{

        //    return View("Index", DepartmentService.Load());
        //}

        public async Task<ActionResult> List()
        {
            IEnumerable<DepartmentDto> departmentDtos = null;

            using (var client = new HttpClient())
            {


                client.BaseAddress = new Uri("https://localhost:44380/api/");
                var result = await client.GetAsync("Department/GetDepartment");

                if (result.IsSuccessStatusCode)
                {
                    departmentDtos = await result.Content.ReadAsAsync<IList<DepartmentDto>>();
                }
                else
                {
                    departmentDtos = Enumerable.Empty<DepartmentDto>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            //return View( "Index",departmentDtos);
            return Json(departmentDtos, JsonRequestBehavior.AllowGet);
        }

        //[Authorize]
        //public ActionResult Create()
        //{
        //    return View();
        //}
        //[Authorize(Roles = "AddDepartment")]
        //[HttpPost]
        //public ActionResult Create(DepartmentDto DeptDto)
        //{
        //    List<DepartmentDto> li = new List<DepartmentDto>();
        //    var DepartmentName = DepartmentService.Load().Where(u => u.Name == DeptDto.Name).FirstOrDefault();

        //    if (DepartmentName == null)
        //    {
        //        DepartmentService.Insert(DeptDto);

        //    }
        //    else
        //    {
        //        //ViewBag.Messagealret = String.Format("the Name has existed");
        //        string msg = "the Name has existed";

        //        //li = DepartmentService.Load();
        //        return Json(new { Message = msg,falied=false});
        //        //return Json(li, JsonRequestBehavior.AllowGet);
        //    }
         
        //    //ViewBag.Message = String.Format("Department Has add");
        //    //li = DepartmentService.Load();
        //    return Json(new { falied = true} );

        //}
        [HttpPost]
        public ActionResult create(DepartmentDto DeptDto)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44380/api/");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<DepartmentDto>("Department/InsertDepartment/", DeptDto);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return Json(new { falied = true });
                }
                else
                {
                    return Json(new {MS= "TJHGF", falied = false });

                }
            }

            //ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
        }
        public ActionResult Delete(int Id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44380/api/");

                var deleteTask = client.DeleteAsync("Department/Delete?Id=" + Id.ToString());
                //var responseTask = client.GetAsync("student?id=" + id.ToString());

                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return Json(new { ssuccess=true });
                }

            }

            return Json(new { MS = "error"});
        }
        //[Authorize]
        //public ActionResult Create()
        //{
        //    return View();
        //}
        //[Authorize(Roles = "AddDepartment")]
        //[HttpPost]
        //public JsonResult CreateAjax(DepartmentDto DeptDto)
        //{
        //    DepartmentService.Insert(DeptDto);
        //    ViewBag.Message = String.Format("Department Has add");
        //    List<DepartmentDto> li = new List<DepartmentDto>();
        //    li = DepartmentService.Load();
        //    //return Json(empDB.Add(emp), JsonRequestBehavior.AllowGet);

        //}
        public ActionResult Find(int Id)
        {
          
            return View("View", DepartmentService.Edit(Id));
        }
        //[Authorize(Roles = "DeleteDepartment")]
 
        //public ActionResult Delete(int Id)
        //{ 
        //    DepartmentService.Delete(Id);
        //    List <DepartmentDto> li = new List<DepartmentDto>();
        //    li = DepartmentService.Load();
        //    ViewBag.MessageDelete = String.Format("Department Has Delete");
        //    return Json( JsonRequestBehavior.AllowGet);
        //}
        //[HttpGet]
        //public ActionResult EditAjax(int Id)
        //{
        //    TempData["IdEmp"] = empolyeeServices.Load().Where(e => e.departmentid == Id).Select(e => e.Id).FirstOrDefault();
        //    TempData["IdRole"] = empolyeeServices.Load().Where(e => e.departmentid == Id).Select(e => e.RoleId).FirstOrDefault();
        //    var IDRole = Convert.ToInt32(TempData["IdRole"]);
          
        //    DepartmentService.Edit(Id);
            
        //    //return View(DepartmentService.Edit(Id));
        //    //var Employee = empDB.ListAll().Find(x => x.EmployeeID.Equals(ID));
        //    return Json(DepartmentService.Edit(Id), JsonRequestBehavior.AllowGet);
        //}






        [HttpGet]
        public async Task< ActionResult >EditAjax(int Id)
        {
            DepartmentDto departmentDtos = null;

            using (var client = new HttpClient())
            {


                client.BaseAddress = new Uri("https://localhost:44380/api/");
                var result = await client.GetAsync("Department/loadBLoadId?Id="+Id.ToString());

                if (result.IsSuccessStatusCode)
                {
                    departmentDtos = await result.Content.ReadAsAsync<DepartmentDto>();
                    return Json(departmentDtos, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    //departmentDtos = Empty(DepartmentDto)();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                    return Json(departmentDtos, JsonRequestBehavior.AllowGet);
                }
            }
            //return View( "Index",departmentDtos);




            //TempData["IdEmp"] = empolyeeServices.Load().Where(e => e.departmentid == Id).Select(e => e.Id).FirstOrDefault();
            //TempData["IdRole"] = empolyeeServices.Load().Where(e => e.departmentid == Id).Select(e => e.RoleId).FirstOrDefault();
            //var IDRole = Convert.ToInt32(TempData["IdRole"]);

            //DepartmentService.Edit(Id);

            ////return View(DepartmentService.Edit(Id));
            ////var Employee = empDB.ListAll().Find(x => x.EmployeeID.Equals(ID));
            //return Json(DepartmentService.Edit(Id), JsonRequestBehavior.AllowGet);


        }


        //[Authorize(Roles = "EditDepartment")]
        //[HttpPost]
        //public ActionResult Edit(DepartmentDto DeptDto)
        //{
        //    var IdEmp = Convert.ToInt32(TempData["IdEmp"]);
        //    DepartmentService.update(DeptDto);
        //    if (IdEmp != 0)
        //    {
        //        var emp = empolyeeServices.Load().Where(y => y.Id == IdEmp).FirstOrDefault();
        //    }
        //    List<DepartmentDto> li = new List<DepartmentDto>();
        //    li = DepartmentService.Load();
        //    return View("Index", li);
        ////}
        ///



        //public IHttpActionResult Put(StudentViewModel student)
        //{
        //    if (!ModelState.IsValid)
        //        return BadRequest("Not a valid model");

        //    using (var ctx = new SchoolDBEntities())
        //    {
        //        var existingStudent = ctx.Students.Where(s => s.StudentID == student.Id)
        //                                                .FirstOrDefault<Student>();

        //        if (existingStudent != null)
        //        {
        //            existingStudent.FirstName = student.FirstName;
        //            existingStudent.LastName = student.LastName;

        //            ctx.SaveChanges();
        //        }
        //        else
        //        {
        //            return NotFound();
        //        }
        //    }

        //    return Ok();
        //}
        //[Authorize(Roles = "EditDepartment")]
        //[HttpPost]
        //public ActionResult Update(DepartmentDto DeptDto)
        //{

        //    var IdEmp = Convert.ToInt32(TempData["IdEmp"]);
        //    DepartmentService.update(DeptDto);
        //    if (IdEmp != 0)
        //    {

Ticketinsystems/Views/Department/Create.cshtml
@model businesslogic.Dto.DepartmentDto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("create", "Department", FormMethod.Post))


{

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "Depname", @name = "Depname" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="Save" name="Save" />
            </div>
        </div>


    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ticketinsystems/Views/Department/CreateAjax.cshtml
@model businesslogic.Dto.DepartmentDto

@{
    ViewBag.Title = "CreateAjax";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateAjax</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepartmentDto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ticketinsystems/Views/Department/Edit.cshtml
@model businesslogic.Dto.DepartmentDto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ticketinsystems/Views/Department/EditAjax.cshtml
@{
    ViewBag.Title = "EditAjax";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditAjax</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken() 
}
<script src="~/Scripts/Department.js"></script>

Ticketinsystems/Views/Department/Index.cshtml
@model IEnumerable<businesslogic.Dto.DepartmentDto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0"" id="Tbl">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Find", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>

}
@if (ViewBag.MessageDelete != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.MessageDelete");
            };
    </script>

}

Ticketinsystems/Views/Department/Index1.cshtml
@{
  
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>


<div class="container">
    <h2>Employees Record</h2>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="clearTextBox();">Add New Department </button><br /><br />
    <table class="table">
        <thead>
            <tr>

                <th>
                    Name
                </th>
            </tr>
        </thead>
        <tbody class="tbody">
        </tbody>
    </table>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="myModalLabel">Add Employee</h4>
                </div>
                <div class="modal-body">
                    <form>

                        <div class="form-group" hidden>
                            <label for="Id">Id</label>
                            <input type="text" class="form-control" id="Id" placeholder="Id" />
                        </div>

                        <div class="form-group">
                            <label for="Name">Name</label>
                            <input type="text" class="form-control" id="Name" placeholder="Name" />
                        </div>


                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                    <button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/Department.js"></script>
@*<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    @section scripts{



        <script src="~/Scripts/Department.js"></script>
        <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap.min.js"></script>
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
                integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
                crossorigin="anonymous"
                referrerpolicy="no-referrer"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#myTable').DataTable();
            });
        </script>
    }*@

Ticketinsystems/Views/Department/View.cshtml
@model businesslogic.Dto.DepartmentDto

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DepartmentDto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(moedl => moedl.Id)



        <div class="form-actions no-color">
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "Delete" })|
            @Html.ActionLink("Cancel", "Index")
        </div>
    }
    @Html.AntiForgeryToken()


</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
        $(document).ready(function () {
            $(".Delete").on("click", function () {
                alert('Are You Sure You Want to Delete this Department??');
            });



       });
</script>